### ISSUE TITLE
Clear times after each submit

### ISSUE THREAD

**Issue by humanfactors** [Akhil-Eaga/FIPS-Data-Entry-System#2]
After each time a user clicks submit, can we clear the entered time data (but not the dates)?

This prevents accidental duplication of entries which currently should be caught out by the soon to be implemented overlap warning.

**Comment by humanfactors** [comment]
Hi @Akhil-Eaga Akhil sorry for delay here!

I think automatically shifting to following day is sensible :)

**Comment by Akhil-Eaga** [comment]
Hi @humanfactors and @lukestrickland,

The prepopulating of input date fields is now implemented. 

When there is no data (like when the user deletes everything or starts to use it for the first time), the date fields are initialized to today and tomorrow. 

when there is some previously saved data, then the last sleep end date in the database is used as the sleep start date and plus one day will be used as sleep end date. 

For example: If the last sleep instance ended on 1st June, then the sleep start date is prefilled to 1st June and the sleep end date is prefilled to 2nd June. 

The time fields are cleared after adding each entry, to prevent users from just mindlessly adding data without even checking. I believe this will help in better quality data input. If you feel this is not a good implemention, please reopen the issue and I will modify it.

Thanks.
